services:
  - type: web
    name: track-invest
    env: static
    # No build command needed since we are using raw HTML/JS
    buildCommand: ""
    # Serves the current root directory
    staticPublishPath: .
    # Rewrites all traffic to your main file (Standard PWA behavior)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
